services:
  heart-api:
    # Build context should be the project root because the Dockerfile copies
    # `backend/` and `Frontend/` paths relative to the repository root.
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # model file lives in the same backend folder as this compose file
      - ./heart_svm_pca_model.pkl:/app/backend/heart_svm_pca_model.pkl:ro
      # frontend directory in the repo is named `Frontend` (capital F)
      - ../Frontend:/app/frontend:ro
    environment:
      - MODEL_PATH=heart_svm_pca_model.pkl
    restart: unless-stopped
